# Generated by Django 2.1.5 on 2019-02-28 14:20

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=29)),
                ('tmax', django_mysql.models.JSONField(default=dict)),
                ('tmin', django_mysql.models.JSONField(default=dict)),
                ('rainfall', django_mysql.models.JSONField(default=dict)),
            ],
        ),
    ]
